In [1]:
# Tutorial for numpy - training for being better prepared to do
# the deep learning training.

import numpy as np



In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
type(a)
print('Rank of a:', a.ndim)

Rank of a: 1


In [9]:
print("Shape of a: ", a.shape)
print("Total number of elements in a: ", a.size)
print("Data type of a: ", a.dtype)

Shape of a:  (3,)
Total number of elements in a:  3
Data type of a:  int64


In [13]:
# Reference an element of a
print(a[0])
print(a[1])
print(a[2])
# illegal cell
# print(a[3])
a[1] = 10
print(a)

1
10
3
[ 1 10  3]


In [14]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]
