Introduction to numpy.

Get more familiar with the library as part of deep learning course.


In [1]:
import numpy as np

In [2]:
# Create evenly spaced n-dimensional array from 1 to 10,
# notice 11 as stop number as this is not included.
A = np.arange(1,11,1)
print(A)
print('Data type of A:', A.dtype)
B = np.arange(1., 2.1, 0.1)
print(B)
print('Data type of B:', B.dtype)

# Whereas arange defines the per value step length, linspace 
# makes an array of the defined number of values spaced equally
C = np.linspace(1, 10, num=20)
print(C)
print ('Data type of C:', C.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
Data type of A: int64
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]
Data type of B: float64
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
Data type of C: float64


In [3]:
# Try out functions for creating data in np arrays
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [4]:
# Create 2 dimensional array of ones. Looks like the dimensions has 
# to be given as a sequence.
twoDimOnes = np.ones((2,5))
print(twoDimOnes)
threeDimOnes = np.ones((2,2,3))
print(threeDimOnes)
# Print one dimension
print(threeDimOnes[0,0])

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[1. 1. 1.]


In [5]:
# There are more functions like this: eye (identity matrix), 
# zeros (all 0)
fullTwoDim = np.full((2,3), 10)
print('fullTwoDim\n', fullTwoDim)

# Then we have random numbers
randomTwoDim = np.random.rand(2,2)
print('ramdomTwoDim:\n', randomTwoDim)

fullTwoDim
 [[10 10 10]
 [10 10 10]]
ramdomTwoDim:
 [[0.0320971  0.96222771]
 [0.25938336 0.91473186]]


In [6]:
# How to read data from file
indata = np.genfromtxt('mydata.dat')

# To iterate on the indata we have some ways to find out the
# sizes of the input matrix: ndim, shape, size
print('ndim: ', indata.ndim)

# The following list holds the result of the shape of indata.
(numlines, valperline) = indata.shape
print('number of lines:', numlines)
print('indata:\n', indata[0])

# print each line 
for lnr in range(0, numlines):
    print('line ', lnr, ':', indata[lnr])
    
# Can do the same with a list
for lnr in (0, 1, 2):
    print ('line ', lnr+1, ':', indata[lnr])

ndim:  2
number of lines: 3
indata:
 [10. 10. 20.]
line  0 : [10. 10. 20.]
line  1 : [30. 40. 50.]
line  2 : [60. 70. 80.]
line  1 : [10. 10. 20.]
line  2 : [30. 40. 50.]
line  3 : [60. 70. 80.]


In [7]:
# Create a matrix
a = np.array([[1, 2, 3],[3,4,6],[7,8,9]])
print(a)
# print upper left
print('upper left:\n', a[:2,:2])
print('lower right:\n', a[1:,1:])
# Notice index starts at 0
print('column 1:\n', a[:,0])

# Using boolean arrays
# Create a boolean array by an expression over a, notice the result
# is a matrix the same rank as a filled with boolean values
aGrThanTwo = (a > 2)
print('a > 2\n', aGrThanTwo, '\nRank aGrThanTwo is ', aGrThanTwo.ndim)

# We can print the values of a for which the expression is true
print(a[aGrThanTwo])
# Or compact
print(a[(a > 2)])
b = a[(a > 2)]
print(b, 'rank b is ', b.ndim)

[[1 2 3]
 [3 4 6]
 [7 8 9]]
upper left:
 [[1 2]
 [3 4]]
lower right:
 [[4 6]
 [8 9]]
column 1:
 [1 3 7]
a > 2
 [[False False  True]
 [ True  True  True]
 [ True  True  True]] 
Rank aGrThanTwo is  2
[3 3 4 6 7 8 9]
[3 3 4 6 7 8 9]
[3 3 4 6 7 8 9] rank b is  1


In [8]:
# Now to mathematical operations on matrixes
# Create a couple of matrixes
a = np.array([[1,1],[2,2],[3,3]])
# b = np.array([[5,5],[5,5],[5,5]])
b = np.full((3,2), 5)

# These are elemnt vise operations (matching elements in each matrix (requires same rank))
print('a:\n', a)
print('b:\n', b)
print('a+b=\n', a+b)
print('np.add(a,b)\n', np.add(a,b))
print('b/5\n', b/5)

a:
 [[1 1]
 [2 2]
 [3 3]]
b:
 [[5 5]
 [5 5]
 [5 5]]
a+b=
 [[6 6]
 [7 7]
 [8 8]]
np.add(a,b)
 [[6 6]
 [7 7]
 [8 8]]
b/5
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# Vector operations
# Create a couple of vectors
v1 = np.array([2,2,3,3,4,4])
v2 = np.array([4,4,4,4,4,4])
print('v1 . v2 = ', np.dot(v1,v2))
print('magnitude(v1) = ', np.dot(v1,v1))
sum = 0
for element in v1:
    sum += element * element
    
print('magnitude_summation(v1) = ', sum)

print('v1 @ v1 = ', v1 @ v1)

v1 . v2 =  72
magnitude(v1) =  58
magnitude_summation(v1) =  58
v1 @ v1 =  58


In [10]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print(A)
A.T

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [11]:

v1 = [1, 2, 3, 4, 5]
#v1 = [2, 2, 2, 2, 2]
A*v1

print('Normal matrix operations')
A_matrix = np.matrix(A)
# Make v1 a column vector
v1_matrix = np.matrix(v1).T
print('Matrix A:\n', A_matrix)
print('Matrix v1:\n', v1_matrix)
type(A_matrix)

Normal matrix operations
Matrix A:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
Matrix v1:
 [[1]
 [2]
 [3]
 [4]
 [5]]


numpy.matrixlib.defmatrix.matrix

In [12]:
A_matrix * v1_matrix

matrix([[ 40],
        [190],
        [340],
        [490],
        [640]])

In [13]:
# Will not work
v1_matrix * A_matrix

ValueError: shapes (5,1) and (5,5) not aligned: 1 (dim 1) != 5 (dim 0)