Welcome to Python 3 tutorial.

In [1]:
import numpy as np

In [2]:
print('hello world')

hello world


In [3]:
A = np.arange(1, 10,2)

In [4]:
A

array([1, 3, 5, 7, 9])

In [7]:
# Create a matrix of 1s with the same shape as A
print ('A shape:', A.shape)
B = np.ones_like(A)
B

A shape: (5,)


array([1, 1, 1, 1, 1])

In [6]:
A+B

array([ 2,  4,  6,  8, 10])