Welcome to Python 3 tutorial.

In [1]:
import numpy as np

In [2]:
print('hello world')

hello world


In [3]:
A = np.arange(1, 10,2)

In [4]:
A

array([1, 3, 5, 7, 9])

In [5]:
# Create a matrix of 1s with the same shape as A
print ('A shape:', A.shape)
B = np.ones_like(A)
B

A shape: (5,)


array([1, 1, 1, 1, 1])

In [6]:
A+B

array([ 2,  4,  6,  8, 10])

In [8]:
M = np.array([[1,1,1],[2,2,2],[3,3,3]])
print('Matrix M:\n', M)

Matrix M:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [11]:
print('Upper left slice of M:\n', M[:1,:1])

Upper left slice of M:
 [[1]]


In [12]:
print('Lower right slice of M:\n', M[1:,1:])

Lower right slice of M:
 [[2 2]
 [3 3]]
